module GMO
  module Const
    INPUT_PARAMS = {
      access_id: "AccessID", access_pass: "AccessPass",
      address_1: "Address1", address_2: "Address2",
      address_3: "Address3", address_4: "Address4",
      address_5: "Address5", address_6: "Address6",
      amount: "Amount", cancel_amount: "CancelAmount",
      cancel_tax: "CancelTax", card_name: "CardName",
      card_no: "CardNo", card_pass: "CardPass",
      card_seq: "CardSeq", client_field_1: "ClientField1",
      client_field_2: "ClientField2", client_field_3: "ClientField3",
      client_field_flg: "ClientFieldFlag", commodity: "Commodity",
      confirm_base_date: "ConfirmBaseDate", continuance_month: "ContinuanceMonth",
      convenience: "Convenience", create_member: "CreateMember",
      currency: "Currency", customer_kana: "CustomerKana",
      customer_name: "CustomerName", default_flag: "DefaultFlag",
      device_category: "DeviceCategory", docomo_disp_1: "DocomoDisp1",
      disp_shop_name: "DispShopName", disp_phone_number: "DispPhoneNumber",
      disp_mail_address: "DispMailAddress", disp_shop_url: "DispShopUrl",
      docomo_disp_2: "DocomoDisp2", eddy_add_info_1: "EdyAddInfo1",
      eddy_add_info_2: "EdyAddInfo2", expire: "Expire",
      first_month_free_flag: "FirstMonthFreeFlag", holder_name: "HolderName",
      http_accept: "HttpAccept", http_user_agent: "HttpUserAgent",
      http_ua: "HttpUserAgent", inquiry_data: "InquiryData",
      inquiry_id: "InquiryID", item_code: "ItemCode",
      item_name: "ItemName", job_cd: "JobCd",
      last_month_free_flag: "LastMonthFreeFlag", locale: "Locale",
      md: "MD", mail_address: "MailAddress",
      member_id: "MemberID", member_name: "MemberName",
      member_no: "MemberNo", method: "Method",
      order_id: "OrderID", pin: "PIN",
      pa_res: "PaRes", pay_times: "PayTimes",
      pay_type: "PayType", payment_term_day: "PaymentTermDay",
      payment_term_sec: "PaymentTermSec", receipts_disp_1: "ReceiptsDisp1",
      redirect_url: "RedirectURL", register_disp_1: "RegisterDisp1",
      register_disp_2: "RegisterDisp2", register_disp_3: "RegisterDisp3",
      register_disp_4: "RegisterDisp4", register_disp_5: "RegisterDisp5",
      register_disp_6: "RegisterDisp6", register_disp_7: "RegisterDisp7",
      register_disp_8: "RegisterDisp8", receipts_disp_9: "ReceiptsDisp9",
      receipts_disp_10: "ReceiptsDisp10", receipts_disp_11: "ReceiptsDisp11",
      receipts_disp_12: "ReceiptsDisp12", receipts_disp_13: "ReceiptsDisp13",
      reserve_no: "ReserveNo", td_tenant_name: "TdTenantName",
      ret_url: "RetURL", security_code: "SecurityCode",
      seq_mode: "SeqMode", service_name: "ServiceName",
      service_tel: "ServiceTel", shop_id: "ShopID",
      shop_mail_address: "ShopMailAddress", shop_pass: "ShopPass",
      site_id: "SiteID", site_pass: "SitePass",
      recurring_id: "RecurringID", charge_start_date: "ChargeStartDate",
      regist_type: "RegistType", src_order_id: "SrcOrderID",
      tax: "Tax", td_flag: "TdFlag",
      token: "Token", charge_day: "ChargeDay",
      account_timing_kbn: "AccountTimingKbn", account_timing: "AccountTiming",
      first_account_date: "FirstAccountDate", first_amount: "FirstAmount",
      tel_no: "TelNo"
    }
  end
end
